[FL]
  full_name = "Florida"

  [[FL.counties]]
    name = "Brevard"
    appraiser_site = "https://www.bcpao.us/PropertySearch/#/nav/Search"

  [[FL.counties]]
    name = "Orange"
    appraiser_site = "http://www.ocpafl.org/searches/ParcelSearch.aspx"

  [[FL.counties]]
    name = "Duval"
    appraiser_site = "https://paopropertysearch.coj.net/Basic/Search.aspx"

  [[FL.counties]]
    name = "Hillsborough"
    appraiser_site = "https://gis.hcpafl.org/propertysearch/#/nav/Basic%20Search"
    
  [[FL.counties]]
    name = "Volusia"    
    http://publicaccess.vcgov.org/volusia/search/commonsearch.aspx?mode=realprop

[GA]
  full_name = "Georgia"

  [[GA.counties]]
    name = "Fulton"
    appraiser_site = "https://iaspublicaccess.fultoncountyga.gov/forms/htmlframe.aspx?mode=content/home.htm"

[NC]
  full_name = "North Carolina"

  [[NC.counties]]
    name = "Mecklenburg"
    appraiser_site = "https://property.spatialest.com/nc/mecklenburg/#/"
