[FL]
  full_name = "Florida"

  [[FL.counties]]
    name = "Brevard"
    appraiser_site = "https://www.bcpao.us/PropertySearch/#/nav/Search"

[GA]
  full_name = "Georgia"

  [[GA.counties]]
    name = "Fulton"
    appraiser_site = "https://iaspublicaccess.fultoncountyga.gov/forms/htmlframe.aspx?mode=content/home.htm"

[NC]
  full_name = "North Carolina"

  [[NC.counties]]
    name = "Mecklenburg"
    appraiser_site = "https://property.spatialest.com/nc/mecklenburg/#/"
