[[county]]
  state_name = "Georgia"
  state_abbreviation = "GA"
  county_name = "Fulton"
  appraiser_site = "https://iaspublicaccess.fultoncountyga.gov/forms/htmlframe.aspx?mode=content/home.htm"

[[county]]
  state_name = "Florida"
  state_abbreviation = "FL"
  county_name = "Brevard"
  appraiser_site = "https://www.bcpao.us/PropertySearch/#/nav/Search"
